# Base image
FROM openjdk:17-alpine

# Set the working directory
WORKDIR /app

# Copy the executable JAR file to the container
COPY ./server.jar /app

# Expose the port the microservice will listen on
EXPOSE 8080

# Set the command to run the microservice when the container starts
CMD ["java", "-jar", "server.jar"]
